### ISSUE TITLE
[todo list]

### ISSUE THREAD

**Issue by ryanburnette** [ryanburnette/eon#1]
- [x] node 16
- [ ] player option so header field player becomes a player
- [ ] player needs to have rel=0 option
- [ ] header fields that become meta tags for custom purposes
- [ ] meta description (create or document)
- [ ] featured image
- [ ] opengraph image (create or document)
- [ ] only show updated date if different day
- [ ] tables, table-container?
- [ ] clean up tables (a bit)
- [ ] numbered lists with code blocks look like crap
- [ ] can we use a different font for "@"
- [ ] sourcemaps as .map files
- [ ] make a .ignore for rg
- [x] fix footer (it has Ryan Burnette hardcoded)
- [ ] start documenting ALL yaml front-matter options
- [ ] fix noindex (if not false)
- [ ] deps should be devDeps
- [ ] add nodemon to deps
- [ ] document noindex
- [x] title should be link back to itself, styled black with no hover to be unobtrusive
- [x] suggest edit link

**Comment by coolaj86** [comment]
Title of article should link to itself (bot content hijacking counter-measure)

probably should strip visual indication (underline, color) since this is intended for bots, not humans

**Comment by coolaj86** [comment]
add `noindex` to docs in README
