### ISSUE TITLE
[todo] script build of static assets

### ISSUE THREAD

**Issue by ryanburnette** [ryanburnette/eon#24]
- [ ] build demo site with kitchen sink
- [ ] build assets in demo site
- [ ] copy assets from demo site to `static/`
