### ISSUE TITLE
[todo] script release process

### ISSUE THREAD

**Issue by ryanburnette** [ryanburnette/eon#25]
- [ ] update package.json with new version
- [ ] npm install
- [ ] version release commit first line is `v[ver]`
- [ ] version release commit bullet points all updates in this release
- [ ] compile and commit static assets with release
