### ISSUE TITLE
[todo] header

### ISSUE THREAD

**Issue by ryanburnette** [ryanburnette/eon#26]
- [ ] double-check header spacing
- [ ] make it so you can set header background with one style
- [ ] make it so the header can be fixed
- [ ] allow a quick change to update header spacing
